apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permitteringsmelding-notifikasjon
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{ version }}
  port: 8080
  ingresses:
    - https://arbeidsgiver.dev.intern.nav.no/permitteringsmelding-notifikasjon
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  gcp:
    sqlInstances:
      - name: permitteringsmelding-notifikasjon
        type: POSTGRES_12
        databases:
          - name: permitteringsmelding-notifikasjon-db
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      rules:
        - application: notifikasjon-produsent-api
          namespace: fager