apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permitteringsvarsel-notifikasjon
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{ version }}
  port: 8080
  ingresses:
    - https://permitteringsvarsel-notifikasjon.dev.intern.nav.no
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  gcp:
    sqlInstances:
      - name: permitteringsvarsel-notifikasjon
        type: POSTGRES_12
        databases:
          - name: permitteringsvarsel-notifikasjon-db
  kafka:
    pool: nav-dev